export const ReasonCode = {
    APPROVED: 'APPROVED',
    ZERO_PAYOUT: 'ZERO_PAYOUT',
    NOT_COVERED: 'NOT_COVERED',
    POLICY_EXPIRED: 'POLICY_EXPIRED',
    POLICY_NOT_ACTIVE: 'POLICY_NOT_ACTIVE',
    POLICY_NOT_FOUND: 'POLICY_NOT_FOUND',
    COVERAGE_LIMIT_EXCEEDED: 'COVERAGE_LIMIT_EXCEEDED',
} as const;
