export const ReasonCode = {
    ZERO_PAYOUT: 'ZERO_PAYOUT',
    NOT_COVERED: 'NOT_COVERED',
    POLICY_EXPIRED: 'POLICY_EXPIRED',
    POLICY_NOT_ACTIVE: 'POLICY_NOT_ACTIVE',
    POLICY_NOT_FOUND: 'POLICY_NOT_FOUND',
} as const;
